<?php
/**
 * SubmittersApi
 * PHP version 7.4
 *
 * @category Class
 * @package  Docuseal
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * DocuSeal API
 *
 * DocuSeal API specs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: admin@docuseal.co
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Docuseal\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Docuseal\ApiException;
use Docuseal\Configuration;
use Docuseal\HeaderSelector;
use Docuseal\ObjectSerializer;

/**
 * SubmittersApi Class Doc Comment
 *
 * @category Class
 * @package  Docuseal
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SubmittersApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'getSubmitter' => [
            'application/json',
        ],
        'getSubmitters' => [
            'application/json',
        ],
        'updateSubmitter' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation getSubmitter
     *
     * Get a submitter
     *
     * @param  int $id The unique identifier of the submitter. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getSubmitter'] to see the possible values for this operation
     *
     * @throws \Docuseal\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Docuseal\Model\GetSubmitter200Response
     */
    public function getSubmitter($id, string $contentType = self::contentTypes['getSubmitter'][0])
    {
        list($response) = $this->getSubmitterWithHttpInfo($id, $contentType);
        return $response;
    }

    /**
     * Operation getSubmitterWithHttpInfo
     *
     * Get a submitter
     *
     * @param  int $id The unique identifier of the submitter. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getSubmitter'] to see the possible values for this operation
     *
     * @throws \Docuseal\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Docuseal\Model\GetSubmitter200Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function getSubmitterWithHttpInfo($id, string $contentType = self::contentTypes['getSubmitter'][0])
    {
        $request = $this->getSubmitterRequest($id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\Docuseal\Model\GetSubmitter200Response' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Docuseal\Model\GetSubmitter200Response' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Docuseal\Model\GetSubmitter200Response', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\Docuseal\Model\GetSubmitter200Response';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Docuseal\Model\GetSubmitter200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getSubmitterAsync
     *
     * Get a submitter
     *
     * @param  int $id The unique identifier of the submitter. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getSubmitter'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getSubmitterAsync($id, string $contentType = self::contentTypes['getSubmitter'][0])
    {
        return $this->getSubmitterAsyncWithHttpInfo($id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getSubmitterAsyncWithHttpInfo
     *
     * Get a submitter
     *
     * @param  int $id The unique identifier of the submitter. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getSubmitter'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getSubmitterAsyncWithHttpInfo($id, string $contentType = self::contentTypes['getSubmitter'][0])
    {
        $returnType = '\Docuseal\Model\GetSubmitter200Response';
        $request = $this->getSubmitterRequest($id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getSubmitter'
     *
     * @param  int $id The unique identifier of the submitter. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getSubmitter'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getSubmitterRequest($id, string $contentType = self::contentTypes['getSubmitter'][0])
    {

        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling getSubmitter'
            );
        }


        $resourcePath = '/submitters/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-Auth-Token');
        if ($apiKey !== null) {
            $headers['X-Auth-Token'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getSubmitters
     *
     * List all submitters
     *
     * @param  int $submission_id The unique identifier of the submission. Allows to receive only submitters for a submission. (optional)
     * @param  string $q Filter submitters on name, email or phone partial match. (optional)
     * @param  string $external_id The unique applications-specific identifier provided for a submitter when initializing a signature request. Allows to receive only submitters with a specified external id. (optional)
     * @param  int $limit The number of submitters to return. Default value is 10. Maximum value is 100. (optional)
     * @param  int $before The unique identifier of the submitter to end the list with. Allows to receive only submitters with id less than the specified value. (optional)
     * @param  int $after The unique identifier of the submitter to start the list from. Allows to receive only submitters with id greater than the specified value. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getSubmitters'] to see the possible values for this operation
     *
     * @throws \Docuseal\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Docuseal\Model\GetSubmitters200Response
     */
    public function getSubmitters($submission_id = null, $q = null, $external_id = null, $limit = null, $before = null, $after = null, string $contentType = self::contentTypes['getSubmitters'][0])
    {
        list($response) = $this->getSubmittersWithHttpInfo($submission_id, $q, $external_id, $limit, $before, $after, $contentType);
        return $response;
    }

    /**
     * Operation getSubmittersWithHttpInfo
     *
     * List all submitters
     *
     * @param  int $submission_id The unique identifier of the submission. Allows to receive only submitters for a submission. (optional)
     * @param  string $q Filter submitters on name, email or phone partial match. (optional)
     * @param  string $external_id The unique applications-specific identifier provided for a submitter when initializing a signature request. Allows to receive only submitters with a specified external id. (optional)
     * @param  int $limit The number of submitters to return. Default value is 10. Maximum value is 100. (optional)
     * @param  int $before The unique identifier of the submitter to end the list with. Allows to receive only submitters with id less than the specified value. (optional)
     * @param  int $after The unique identifier of the submitter to start the list from. Allows to receive only submitters with id greater than the specified value. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getSubmitters'] to see the possible values for this operation
     *
     * @throws \Docuseal\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Docuseal\Model\GetSubmitters200Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function getSubmittersWithHttpInfo($submission_id = null, $q = null, $external_id = null, $limit = null, $before = null, $after = null, string $contentType = self::contentTypes['getSubmitters'][0])
    {
        $request = $this->getSubmittersRequest($submission_id, $q, $external_id, $limit, $before, $after, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\Docuseal\Model\GetSubmitters200Response' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Docuseal\Model\GetSubmitters200Response' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Docuseal\Model\GetSubmitters200Response', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\Docuseal\Model\GetSubmitters200Response';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Docuseal\Model\GetSubmitters200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getSubmittersAsync
     *
     * List all submitters
     *
     * @param  int $submission_id The unique identifier of the submission. Allows to receive only submitters for a submission. (optional)
     * @param  string $q Filter submitters on name, email or phone partial match. (optional)
     * @param  string $external_id The unique applications-specific identifier provided for a submitter when initializing a signature request. Allows to receive only submitters with a specified external id. (optional)
     * @param  int $limit The number of submitters to return. Default value is 10. Maximum value is 100. (optional)
     * @param  int $before The unique identifier of the submitter to end the list with. Allows to receive only submitters with id less than the specified value. (optional)
     * @param  int $after The unique identifier of the submitter to start the list from. Allows to receive only submitters with id greater than the specified value. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getSubmitters'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getSubmittersAsync($submission_id = null, $q = null, $external_id = null, $limit = null, $before = null, $after = null, string $contentType = self::contentTypes['getSubmitters'][0])
    {
        return $this->getSubmittersAsyncWithHttpInfo($submission_id, $q, $external_id, $limit, $before, $after, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getSubmittersAsyncWithHttpInfo
     *
     * List all submitters
     *
     * @param  int $submission_id The unique identifier of the submission. Allows to receive only submitters for a submission. (optional)
     * @param  string $q Filter submitters on name, email or phone partial match. (optional)
     * @param  string $external_id The unique applications-specific identifier provided for a submitter when initializing a signature request. Allows to receive only submitters with a specified external id. (optional)
     * @param  int $limit The number of submitters to return. Default value is 10. Maximum value is 100. (optional)
     * @param  int $before The unique identifier of the submitter to end the list with. Allows to receive only submitters with id less than the specified value. (optional)
     * @param  int $after The unique identifier of the submitter to start the list from. Allows to receive only submitters with id greater than the specified value. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getSubmitters'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getSubmittersAsyncWithHttpInfo($submission_id = null, $q = null, $external_id = null, $limit = null, $before = null, $after = null, string $contentType = self::contentTypes['getSubmitters'][0])
    {
        $returnType = '\Docuseal\Model\GetSubmitters200Response';
        $request = $this->getSubmittersRequest($submission_id, $q, $external_id, $limit, $before, $after, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getSubmitters'
     *
     * @param  int $submission_id The unique identifier of the submission. Allows to receive only submitters for a submission. (optional)
     * @param  string $q Filter submitters on name, email or phone partial match. (optional)
     * @param  string $external_id The unique applications-specific identifier provided for a submitter when initializing a signature request. Allows to receive only submitters with a specified external id. (optional)
     * @param  int $limit The number of submitters to return. Default value is 10. Maximum value is 100. (optional)
     * @param  int $before The unique identifier of the submitter to end the list with. Allows to receive only submitters with id less than the specified value. (optional)
     * @param  int $after The unique identifier of the submitter to start the list from. Allows to receive only submitters with id greater than the specified value. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getSubmitters'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getSubmittersRequest($submission_id = null, $q = null, $external_id = null, $limit = null, $before = null, $after = null, string $contentType = self::contentTypes['getSubmitters'][0])
    {








        $resourcePath = '/submitters';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $submission_id,
            'submission_id', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $q,
            'q', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $external_id,
            'external_id', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $limit,
            'limit', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $before,
            'before', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $after,
            'after', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-Auth-Token');
        if ($apiKey !== null) {
            $headers['X-Auth-Token'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation updateSubmitter
     *
     * Update a submitter
     *
     * @param  int $id The unique identifier of the submitter. (required)
     * @param  \Docuseal\Model\UpdateSubmitterRequest $update_submitter_request update_submitter_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateSubmitter'] to see the possible values for this operation
     *
     * @throws \Docuseal\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Docuseal\Model\UpdateSubmitter200Response
     */
    public function updateSubmitter($id, $update_submitter_request, string $contentType = self::contentTypes['updateSubmitter'][0])
    {
        list($response) = $this->updateSubmitterWithHttpInfo($id, $update_submitter_request, $contentType);
        return $response;
    }

    /**
     * Operation updateSubmitterWithHttpInfo
     *
     * Update a submitter
     *
     * @param  int $id The unique identifier of the submitter. (required)
     * @param  \Docuseal\Model\UpdateSubmitterRequest $update_submitter_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateSubmitter'] to see the possible values for this operation
     *
     * @throws \Docuseal\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Docuseal\Model\UpdateSubmitter200Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function updateSubmitterWithHttpInfo($id, $update_submitter_request, string $contentType = self::contentTypes['updateSubmitter'][0])
    {
        $request = $this->updateSubmitterRequest($id, $update_submitter_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\Docuseal\Model\UpdateSubmitter200Response' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Docuseal\Model\UpdateSubmitter200Response' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Docuseal\Model\UpdateSubmitter200Response', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\Docuseal\Model\UpdateSubmitter200Response';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Docuseal\Model\UpdateSubmitter200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation updateSubmitterAsync
     *
     * Update a submitter
     *
     * @param  int $id The unique identifier of the submitter. (required)
     * @param  \Docuseal\Model\UpdateSubmitterRequest $update_submitter_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateSubmitter'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updateSubmitterAsync($id, $update_submitter_request, string $contentType = self::contentTypes['updateSubmitter'][0])
    {
        return $this->updateSubmitterAsyncWithHttpInfo($id, $update_submitter_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation updateSubmitterAsyncWithHttpInfo
     *
     * Update a submitter
     *
     * @param  int $id The unique identifier of the submitter. (required)
     * @param  \Docuseal\Model\UpdateSubmitterRequest $update_submitter_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateSubmitter'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updateSubmitterAsyncWithHttpInfo($id, $update_submitter_request, string $contentType = self::contentTypes['updateSubmitter'][0])
    {
        $returnType = '\Docuseal\Model\UpdateSubmitter200Response';
        $request = $this->updateSubmitterRequest($id, $update_submitter_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'updateSubmitter'
     *
     * @param  int $id The unique identifier of the submitter. (required)
     * @param  \Docuseal\Model\UpdateSubmitterRequest $update_submitter_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateSubmitter'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function updateSubmitterRequest($id, $update_submitter_request, string $contentType = self::contentTypes['updateSubmitter'][0])
    {

        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling updateSubmitter'
            );
        }

        // verify the required parameter 'update_submitter_request' is set
        if ($update_submitter_request === null || (is_array($update_submitter_request) && count($update_submitter_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $update_submitter_request when calling updateSubmitter'
            );
        }


        $resourcePath = '/submitters/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($update_submitter_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($update_submitter_request));
            } else {
                $httpBody = $update_submitter_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-Auth-Token');
        if ($apiKey !== null) {
            $headers['X-Auth-Token'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'PUT',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
