<?php
/**
 * CreateSubmission200ResponseInnerPreferencesTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Docuseal
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * DocuSeal API
 *
 * DocuSeal API specs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: admin@docuseal.co
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Docuseal\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * CreateSubmission200ResponseInnerPreferencesTest Class Doc Comment
 *
 * @category    Class
 * @description CreateSubmission200ResponseInnerPreferences
 * @package     Docuseal
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class CreateSubmission200ResponseInnerPreferencesTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "CreateSubmission200ResponseInnerPreferences"
     */
    public function testCreateSubmission200ResponseInnerPreferences()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "send_email"
     */
    public function testPropertySendEmail()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "send_sms"
     */
    public function testPropertySendSms()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
