<?php
/**
 * CreateTemplateFromDocxRequestDocumentsInnerFieldsInnerAreasInnerTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Docuseal
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * DocuSeal API
 *
 * DocuSeal API specs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: admin@docuseal.co
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Docuseal\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * CreateTemplateFromDocxRequestDocumentsInnerFieldsInnerAreasInnerTest Class Doc Comment
 *
 * @category    Class
 * @description CreateTemplateFromDocxRequestDocumentsInnerFieldsInnerAreasInner
 * @package     Docuseal
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class CreateTemplateFromDocxRequestDocumentsInnerFieldsInnerAreasInnerTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "CreateTemplateFromDocxRequestDocumentsInnerFieldsInnerAreasInner"
     */
    public function testCreateTemplateFromDocxRequestDocumentsInnerFieldsInnerAreasInner()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "x"
     */
    public function testPropertyX()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "y"
     */
    public function testPropertyY()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "w"
     */
    public function testPropertyW()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "h"
     */
    public function testPropertyH()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "page"
     */
    public function testPropertyPage()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
