<?php
/**
 * CreateTemplateFromDocxRequestDocumentsInnerFieldsInnerTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Docuseal
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * DocuSeal API
 *
 * DocuSeal API specs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: admin@docuseal.co
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Docuseal\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * CreateTemplateFromDocxRequestDocumentsInnerFieldsInnerTest Class Doc Comment
 *
 * @category    Class
 * @description CreateTemplateFromDocxRequestDocumentsInnerFieldsInner
 * @package     Docuseal
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class CreateTemplateFromDocxRequestDocumentsInnerFieldsInnerTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "CreateTemplateFromDocxRequestDocumentsInnerFieldsInner"
     */
    public function testCreateTemplateFromDocxRequestDocumentsInnerFieldsInner()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "role"
     */
    public function testPropertyRole()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "areas"
     */
    public function testPropertyAreas()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
