<?php
/**
 * SubmissionsApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Docuseal
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * DocuSeal API
 *
 * DocuSeal API specs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: admin@docuseal.co
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Docuseal\Test\Api;

use \Docuseal\Configuration;
use \Docuseal\ApiException;
use \Docuseal\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * SubmissionsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Docuseal
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SubmissionsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for archiveSubmission
     *
     * Archive a submission.
     *
     */
    public function testArchiveSubmission()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createSubmission
     *
     * Create a submission.
     *
     */
    public function testCreateSubmission()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createSubmissionsFromEmails
     *
     * Create submissions from emails.
     *
     */
    public function testCreateSubmissionsFromEmails()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getSubmission
     *
     * Get a submission.
     *
     */
    public function testGetSubmission()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getSubmissions
     *
     * List all submissions.
     *
     */
    public function testGetSubmissions()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
