<?php
/**
 * TemplatesApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Docuseal
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * DocuSeal API
 *
 * DocuSeal API specs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: admin@docuseal.co
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Docuseal\Test\Api;

use \Docuseal\Configuration;
use \Docuseal\ApiException;
use \Docuseal\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * TemplatesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Docuseal
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class TemplatesApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for addDocumentToTemplate
     *
     * Add new document to template.
     *
     */
    public function testAddDocumentToTemplate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for archiveTemplate
     *
     * Archive a template.
     *
     */
    public function testArchiveTemplate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for cloneTemplate
     *
     * Clone a template.
     *
     */
    public function testCloneTemplate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createTemplateFromDocx
     *
     * Create a template from Word DOCX.
     *
     */
    public function testCreateTemplateFromDocx()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createTemplateFromHtml
     *
     * Create a template from HTML.
     *
     */
    public function testCreateTemplateFromHtml()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createTemplateFromPdf
     *
     * Create a template from existing PDF.
     *
     */
    public function testCreateTemplateFromPdf()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getTemplate
     *
     * Get a template.
     *
     */
    public function testGetTemplate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getTemplates
     *
     * List all templates.
     *
     */
    public function testGetTemplates()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateTemplate
     *
     * Update a template.
     *
     */
    public function testUpdateTemplate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
